# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _algorithm_from_cpp
else:
    import _algorithm_from_cpp

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _algorithm_from_cpp.delete_SwigPyIterator

    def value(self):
        return _algorithm_from_cpp.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _algorithm_from_cpp.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _algorithm_from_cpp.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _algorithm_from_cpp.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _algorithm_from_cpp.SwigPyIterator_equal(self, x)

    def copy(self):
        return _algorithm_from_cpp.SwigPyIterator_copy(self)

    def next(self):
        return _algorithm_from_cpp.SwigPyIterator_next(self)

    def __next__(self):
        return _algorithm_from_cpp.SwigPyIterator___next__(self)

    def previous(self):
        return _algorithm_from_cpp.SwigPyIterator_previous(self)

    def advance(self, n):
        return _algorithm_from_cpp.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _algorithm_from_cpp.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _algorithm_from_cpp.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _algorithm_from_cpp.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _algorithm_from_cpp.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _algorithm_from_cpp.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _algorithm_from_cpp.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _algorithm_from_cpp:
_algorithm_from_cpp.SwigPyIterator_swigregister(SwigPyIterator)
class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _algorithm_from_cpp.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _algorithm_from_cpp.IntVector___nonzero__(self)

    def __bool__(self):
        return _algorithm_from_cpp.IntVector___bool__(self)

    def __len__(self):
        return _algorithm_from_cpp.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _algorithm_from_cpp.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _algorithm_from_cpp.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _algorithm_from_cpp.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _algorithm_from_cpp.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _algorithm_from_cpp.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _algorithm_from_cpp.IntVector___setitem__(self, *args)

    def pop(self):
        return _algorithm_from_cpp.IntVector_pop(self)

    def append(self, x):
        return _algorithm_from_cpp.IntVector_append(self, x)

    def empty(self):
        return _algorithm_from_cpp.IntVector_empty(self)

    def size(self):
        return _algorithm_from_cpp.IntVector_size(self)

    def swap(self, v):
        return _algorithm_from_cpp.IntVector_swap(self, v)

    def begin(self):
        return _algorithm_from_cpp.IntVector_begin(self)

    def end(self):
        return _algorithm_from_cpp.IntVector_end(self)

    def rbegin(self):
        return _algorithm_from_cpp.IntVector_rbegin(self)

    def rend(self):
        return _algorithm_from_cpp.IntVector_rend(self)

    def clear(self):
        return _algorithm_from_cpp.IntVector_clear(self)

    def get_allocator(self):
        return _algorithm_from_cpp.IntVector_get_allocator(self)

    def pop_back(self):
        return _algorithm_from_cpp.IntVector_pop_back(self)

    def erase(self, *args):
        return _algorithm_from_cpp.IntVector_erase(self, *args)

    def __init__(self, *args):
        _algorithm_from_cpp.IntVector_swiginit(self, _algorithm_from_cpp.new_IntVector(*args))

    def push_back(self, x):
        return _algorithm_from_cpp.IntVector_push_back(self, x)

    def front(self):
        return _algorithm_from_cpp.IntVector_front(self)

    def back(self):
        return _algorithm_from_cpp.IntVector_back(self)

    def assign(self, n, x):
        return _algorithm_from_cpp.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _algorithm_from_cpp.IntVector_resize(self, *args)

    def insert(self, *args):
        return _algorithm_from_cpp.IntVector_insert(self, *args)

    def reserve(self, n):
        return _algorithm_from_cpp.IntVector_reserve(self, n)

    def capacity(self):
        return _algorithm_from_cpp.IntVector_capacity(self)
    __swig_destroy__ = _algorithm_from_cpp.delete_IntVector

# Register IntVector in _algorithm_from_cpp:
_algorithm_from_cpp.IntVector_swigregister(IntVector)
class vec_in_vec(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _algorithm_from_cpp.vec_in_vec_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _algorithm_from_cpp.vec_in_vec___nonzero__(self)

    def __bool__(self):
        return _algorithm_from_cpp.vec_in_vec___bool__(self)

    def __len__(self):
        return _algorithm_from_cpp.vec_in_vec___len__(self)

    def __getslice__(self, i, j):
        return _algorithm_from_cpp.vec_in_vec___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _algorithm_from_cpp.vec_in_vec___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _algorithm_from_cpp.vec_in_vec___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _algorithm_from_cpp.vec_in_vec___delitem__(self, *args)

    def __getitem__(self, *args):
        return _algorithm_from_cpp.vec_in_vec___getitem__(self, *args)

    def __setitem__(self, *args):
        return _algorithm_from_cpp.vec_in_vec___setitem__(self, *args)

    def pop(self):
        return _algorithm_from_cpp.vec_in_vec_pop(self)

    def append(self, x):
        return _algorithm_from_cpp.vec_in_vec_append(self, x)

    def empty(self):
        return _algorithm_from_cpp.vec_in_vec_empty(self)

    def size(self):
        return _algorithm_from_cpp.vec_in_vec_size(self)

    def swap(self, v):
        return _algorithm_from_cpp.vec_in_vec_swap(self, v)

    def begin(self):
        return _algorithm_from_cpp.vec_in_vec_begin(self)

    def end(self):
        return _algorithm_from_cpp.vec_in_vec_end(self)

    def rbegin(self):
        return _algorithm_from_cpp.vec_in_vec_rbegin(self)

    def rend(self):
        return _algorithm_from_cpp.vec_in_vec_rend(self)

    def clear(self):
        return _algorithm_from_cpp.vec_in_vec_clear(self)

    def get_allocator(self):
        return _algorithm_from_cpp.vec_in_vec_get_allocator(self)

    def pop_back(self):
        return _algorithm_from_cpp.vec_in_vec_pop_back(self)

    def erase(self, *args):
        return _algorithm_from_cpp.vec_in_vec_erase(self, *args)

    def __init__(self, *args):
        _algorithm_from_cpp.vec_in_vec_swiginit(self, _algorithm_from_cpp.new_vec_in_vec(*args))

    def push_back(self, x):
        return _algorithm_from_cpp.vec_in_vec_push_back(self, x)

    def front(self):
        return _algorithm_from_cpp.vec_in_vec_front(self)

    def back(self):
        return _algorithm_from_cpp.vec_in_vec_back(self)

    def assign(self, n, x):
        return _algorithm_from_cpp.vec_in_vec_assign(self, n, x)

    def resize(self, *args):
        return _algorithm_from_cpp.vec_in_vec_resize(self, *args)

    def insert(self, *args):
        return _algorithm_from_cpp.vec_in_vec_insert(self, *args)

    def reserve(self, n):
        return _algorithm_from_cpp.vec_in_vec_reserve(self, n)

    def capacity(self):
        return _algorithm_from_cpp.vec_in_vec_capacity(self)
    __swig_destroy__ = _algorithm_from_cpp.delete_vec_in_vec

# Register vec_in_vec in _algorithm_from_cpp:
_algorithm_from_cpp.vec_in_vec_swigregister(vec_in_vec)

def LouvainCommunityDetect(Edge, node_num):
    return _algorithm_from_cpp.LouvainCommunityDetect(Edge, node_num)

def LabelPropagation(Edge, node_num):
    return _algorithm_from_cpp.LabelPropagation(Edge, node_num)

